---
# Use with pre-commit.
# See usage instructions at https://pre-commit.com

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/prettier/prettier
  rev: "2.0.5" # Use the checksum or tag from the git repository.
  hooks:
    - id: prettier
      name: prettier
      entry: prettier --write
      language: node
      # https://github.com/prettier/prettier/blob/master/.pre-commit-hooks.yaml
      files: "\\.(\
        css|less|scss\
        |graphql|gql\
        |html\
        |js|jsx\
        |json\
        |md|markdown|mdown|mkdn\
        |mdx\
        |ts|tsx\
        |vue\
        )$"
      # exclude: .pre-commit-config.yaml

- repo: local
  hooks:
    - id: yamllint
      name: yamllint
      description: This hook runs yamllint.
      entry: yamllint
      args: [--config-file=.yamllint.yaml]
      language: python
      types: [file, yaml]
