---
name: Build Container Image
on:
  push:
    branches:
      - master
    paths:
      - "Dockerfile"
      - "entrypoint.sh"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: sheeeng/github-actions-yamllint
      DOCKER_FILE: Dockerfile
    steps:
      - uses: actions/checkout@v1
      - name: Build the yamllint container image.
        run: |
          docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_TOKEN }}
          docker build . --file $DOCKER_FILE -t $DOCKER_IMAGE:$GITHUB_SHA -t $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:$GITHUB_SHA
          docker push $DOCKER_IMAGE:latest
